#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := esp_settings

EXTRA_COMPONENT_DIRS := $(CURDIR)/../..

include $(IDF_PATH)/make/project.mk
